### ISSUE TITLE
very long edges 

### ISSUE THREAD

**Issue by MatteoRomiti** [graphsense/graphsense-dashboard#102]
Example: Add the poloniex cluster, then the notpetya cluster and then click the outgoing neighbors of this last one. I get very long edges to the outgoing neighbors on Chrome and on Firefox

**Comment by MatteoRomiti** [comment]
I still get the problem, is it solved?

**Comment by myrho** [comment]
At least, I'm not getting long edges for the example above. Do you have another one?

**Comment by MatteoRomiti** [comment]
OK, it is solved but not deployed yet.
