### ISSUE TITLE
tag annotation 

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#118]
add menu item to address context menu to fill out tagpack fields. Autocomplete label with existing labels (then auto-choose category).

**Comment by myrho** [comment]
Remove "add notes" from menus on entities and addresses, instead "annotate". On entity this leads to simple note taking, on address to tagpack tag creation.

**Comment by myrho** [comment]
* Add fields for tagpack fields: 
  * dropdown of categories,
  * source
  * abuse
* remove keyspace fields from tagpack
* move fields with same values to top level of tagpack
* creator (to be defined when tagpack is exported)
* "Add note" -> "Annotate"
* include user-defined tags in autocomplete

**Comment by myrho** [comment]
fix last modified timestamp on user defined tag

**Comment by myrho** [comment]
if user selects a label from search, disable category, abuse and source form fields

**Comment by myrho** [comment]
@behas 
we agreed to disable category, abuse and source form fields if user selects an non user-defined label (from search). But a label itself is not associated with any of these data. So how should these be filled for the created tag?

**Comment by behas** [comment]
Sorry, I understand the question. Could you provide an example?
________________________________________

**Comment by myrho** [comment]
Say user enters "Locky" in the search bar within the annotation box, then a tag is created for this address. The tag's label is "Locky" but what about category, abuse and source?
