### ISSUE TITLE
Not able to re-add an address to the graph after removing it 

### ISSUE THREAD

**Issue by MatteoRomiti** [graphsense/graphsense-dashboard#126]
Starting from one address (15ebQxsrRRUwYFaqfmcgbC2hnYrq6Y72oM), if I click on one of the outgoing addresses (39ngTt6DWQRUbzjmx6ucxz7pPvQcm52CL3 (first address when sorting by decreasing received BTC)), it appears in the graph, as expected. If I then remove this outgoing address (right click -> remove) and I select it again from the list of outgoing addresses, it does not reappear in the graph.

**Comment by myrho** [comment]
I can't reproduce in beta.

**Comment by MatteoRomiti** [comment]
That's true.
