### ISSUE TITLE
Load and display (bigger) Cluster in Dashboard

### ISSUE THREAD

**Issue by PatrickSchre** [graphsense/graphsense-dashboard#131]
Hi all,
lately there are occuring a lot of problems with loading bigger clusters in the dashboard. Some times it doesn´t load even there are 2 or 3 bigger clusters in one graph. Mostly it happens, when it´s the same cluster which sould be loaded.
Due to that high workload, sometimes it´s not even more possible so save the graph, which I am working on.
If someone is interessted in, I can send you a screenshot.
If it is a backend/cassandra issue, please feel free to switch it.

**Comment by myrho** [comment]
Hi Patrick,
yes, please send me a screenshot to dev@pisys.eu.
What do you mean by "bigger" cluster? Many addresses being displayed?

**Comment by PatrickSchre** [comment]
Hi Matthias,
I will send it today to you.
I have noticed that graphsense can not load, respectively connect two cluster, if there is one or more nodes between there. i.e. I have cluster A, B and C in a graph. These three are connected and have many other transactions. Now I see, that cluster A also made a trx directly to cluster C. Graphsense cann´t display it and the workload will get bigger and bigger. Maybe that s the cause? Nevertheless, it would be great to connect clusters without direct edges.

**Comment by PatrickSchre** [comment]
Corrct, cluster which includes many addresses and transactions
