### ISSUE TITLE
Unable to export a cluster

### ISSUE THREAD

**Issue by blatherdrift** [graphsense/graphsense-dashboard#154]
Hello!

I was hoping to use GraphSense to export a known, but unnamed cluster into csv format to be parsed and run through neo4j but I couldn't find any way to do this.

Does this feature exist? If not, could you consider adding it? 

thank you!

**Comment by myrho** [comment]
Thank you for your interest in GraphSense!

I'm not sure whether I understand your notion of cluster correctly. What kind of CSV (headers, data types) would you expect? Could you give an example?

**Comment by blatherdrift** [comment]
Yes. Let me elaborate.

A node with an entity number of 217186679 is displayed as containing 86 addresses. I considered that a cluster of addresses because it's displayed as a single node. i can get a list of the addresses by clicking the @ symbol but I'd like to be able to export those addresses, working under the assumption that they are a cluster found by one of the clustering heuristics. I'm not given that option; there is no export feature like we have with outgoing entities, for example. I'd like for the addresses tab to have a csv button, too.

**Comment by myrho** [comment]
Ok I see. This should not be a big deal. We will consider adding it for the next release.

**Comment by myrho** [comment]
As of 0.4.5 addresses of a cluster can now be exported as CSV.
