### ISSUE TITLE
Error in transaction estimated values

### ISSUE THREAD

**Issue by CarlosLannister** [graphsense/graphsense-dashboard#156]
Hi, 

Using graphene is it possible to show the estimated value of transactions and represent these values using COIN, EUR and USD.

![image](https://user-images.githubusercontent.com/2520132/93591925-8b4f9e80-f9b1-11ea-8265-e378b5cd6394.png)

In this case, BTC address, 13AM4VW2dhxYgXeQepoHkHSQuy6NgaEb94, had received 20.0658 BTC and have a current balance of 0.3207 BTC. There are three transactions flows with 10.058, 9.5629 and 0.1029 BTC making a total 19,7238 BTC. 

My question/problem came when you transform those values to EUR or USD. 

![image](https://user-images.githubusercontent.com/2520132/93593005-8a1f7100-f9b3-11ea-81ea-77228118b6ee.png)

The Total received is 34,022.68 USD and the outcoming transactions are 28,306.85, 26,913.32 and 289.53 USD, making a total of 55,509.7 USD. 

At least for me, this does not make any sense. I do not know which BTC/USD conversions values are being used but 10.058 BTC should be around 110533,40 USD, not 28,306.85 USD. 

PS: I am using the https://demo.graphsense.info/ version.

**Comment by defconst** [comment]
The value 10.058 BTC comes from tx `8def6458a46234ab0e040602e7852ff5cf58650f3f1102803b1d4bca4cc293a1` (height 478795, 2017-08-03 04:28:20 UTC). The exchange rates at this time were 2370.787 EUR and 2814.3613 USD respectively.

**Comment by CarlosLannister** [comment]
Ok, so if I understand correctly the transaction label, when you select show the estimated value, uses the exchange rates at the moment of the transaction. 

But, what conversion rate uses the Total Received value of an address, like 13AM4VW2dhxYgXeQepoHkHSQuy6NgaEb94?. This address received 20,0658 BTC and graphsense estimated that into 37.688,54 USD.

**Comment by defconst** [comment]
Total received uses the same principle:
`tx_in` are all incoming transactions (length `n`) for the address;
for each incoming tx `tx_in[i]` at height `h[i]` we convert the value `tx_in[i].value` with exchange rate `er[i]` (at height `h[i]`).
The converted value for total received is then `sum_{i=1}^{n}(tx[i].value/1e8 * er[i])`.

**Comment by defconst** [comment]
Total received uses the same principle:
tx_in are all incoming transactions (length n) for the address; for each incoming tx tx_in[i] at height h[i] we convert the value tx_in[i].value with exchange rate er[i] (at height h[i]).
The converted value for total received is then sum_{i=1}^{n}(tx_in[i].value/1e8 * er[i]).

**Comment by CarlosLannister** [comment]
Thank you very much, I did not understand wich exchange rates were being used. Now it is perfectly clear, sorry for the trouble.
