### ISSUE TITLE
Infobox not working under MS Edge

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#166]

**Comment by behas** [comment]
![image](https://user-images.githubusercontent.com/366981/105851075-dd996f80-5fe2-11eb-8776-7e06d14e6443.png)

**Comment by behas** [comment]
Version: 0.86.0.622.58

**Comment by myrho** [comment]
This actually is a feature. Only categories of present nodes are shown. So if there aren't any nodes with categories (tags), the legend is empty. However, the empty legend is also confusing. Possible solutions imho are (in order of preference):

- the legend icon in the header should only appear/be enabled if the legend is not empty (ie. tagged nodes are present in the graph)
- the legend should yield a message like "Legend empty (no tagged nodes present yet)"
- the legend should always yield all categories irresp. of present nodes (this could get a long and probably may contain information irrelevant to the user)
