### ISSUE TITLE
Improve address / entity annotation handling

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#168]
Address Tag = a complex object assigned to **addresses** (organized in tagpacks, ingested during transformation; can also be entered by the user.

Cluster Label = a human-readable label denoting the meaning of a **cluster** (e.g., name of an exchange) -> added **manually** by the dashboard user; stored in local in-browser TagStore; it should be possible to export and re-load tags; cluster labels are linked to cluster IDs = minimum address ID (lookup address for address ID)

**Comment by myrho** [comment]
you mean "lookup cluster for address ID", right?

**Comment by myrho** [comment]
Cluster tag is just a label and a category

**Comment by myrho** [comment]
Implemented:
* Tables for local entity/address tags
* Entities have "Entity tags" and "Address tags". Latter are aggregated from the contained addresses' tags.
* Existing notes on entities are turned into entity tags
* `Search for neighbors` feature also takes local entity tags into account
* GraphSense REST also hosts entity tags
