### ISSUE TITLE
Address tagging | Categories not shown

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#180]
At the moment no entity and abuse categories are shown when tagging an address.

![image](https://user-images.githubusercontent.com/366981/116365128-3d333100-a805-11eb-9530-5bd7a1cd9871.png)

**Comment by myrho** [comment]
That's already fixed by #172. I just need to pick it from develop.

**Comment by myrho** [comment]
Actually the taxonomy `abuse` seems not to exist anymore in the tagpacks keyspace.

**Comment by myrho** [comment]
Fixed by `hotfix-181`
