### ISSUE TITLE
TagPack Import | Categories not updated

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#181]
When loading a TagPack with address categories (entity, abuse), then the categories are not shown in the categories info box

**Comment by myrho** [comment]
By categories info box you mean the legend at top right?

**Comment by behas** [comment]
exactly.

**Comment by myrho** [comment]
Maybe it's actually a feature:
1. Legend only contains categories of nodes present in the graph (so keep the legend concise), see also #166 
2. Categories not present in the `tagpacks` keyspace can not be shown at all (eg. user defined categories ingested through tagpack yamls)

**Comment by myrho** [comment]
Fixed by `hotfix-181`
