### ISSUE TITLE
Search property settings

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#201]
Selection of "breadth" and "Skip entities with more addresses than" is currently bound to each other: increasing one value increases also the other.

Proposed solution:
- both fields should support independent int value inputs

Also: rename "Skip entities with more addresses than" -> "Max. Addresses"

![image](https://user-images.githubusercontent.com/366981/120203328-e4055580-c227-11eb-8da9-2446688731c0.png)

**Comment by myrho** [comment]
Fixed
