### ISSUE TITLE
UX issue: saving tags is counter-intuitive

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#204]
Tags added to entities and addresses via the "annotate" menu item, are neither displayed in the Graph nor in the Local Tagstore,

**Comment by myrho** [comment]
Can't reproduce.

1. Right click node -> Annotate
2. Enter label -> Hit Enter/"+"
3. Optionally fill fields
4. Save
5. Click "my address/entity tags" in the left sidebar -> tags are shown

**Comment by behas** [comment]
This seems to be counter-intuitive and has also been reported by another user:

Wenn ich auf „Annotate“ gehe und ein „Label“ eintrage, kommt ein Ladesymbol und das Feld „Save“ ist ausgegraut mit Verbotssymbol. Nun habe ich herausgefunden, dass man anscheinend vorher auf das Pluszeichen klicken muss. Dann trage ich das Label ein und kann auf „Save“ clicken. Diesen Vorgang muss ich jedoch noch einmal wiederholen, dass das Tag auch angezeigt wird. Beim ersten Durchgang existiert das Labelfeld zwar, ist dann aber leer.

**Comment by behas** [comment]
@myrho please check if we include in 0.5.1
