### ISSUE TITLE
Loaded TagPacks don't show up in my tags

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#225]
If a user loads tags from a local tagpack file, loaded tags do not show up under "my tags".

**Comment by myrho** [comment]
That's a feature actually. The "my tags" table is for tags defined by the user in the current session (see #168).
But if you'd expect tagpack tags to show up there we should rethink the purpose of the table at all. Probably in the next iteration with the general redesign of tag stores.
