### ISSUE TITLE
Mismatch between displayed and checked entities

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#233]
After removing entities from the graph, they are still checked in the property box but not displayed anymore. After deletion they cannot be re-added anymore.

![image](https://user-images.githubusercontent.com/366981/142487157-8bb03594-9aa9-4abc-8eb1-7b2ebc3b5e79.png)

**Comment by myrho** [comment]
I can't reproduce unfortunately. How did you get there?

**Comment by behas** [comment]
cannot reproduce either; will keep and postpone the issue in case it appears again
