### ISSUE TITLE
Account Model Address / Entity View | Wrong value conversion

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#244]
Wrong ETH value conversion on the dashboard. Example address: 0x564286362092d8e7936f0549571a803b203aaced

- EtherScan balance: 0.20 ETH (https://etherscan.io/address/0x564286362092d8e7936f0549571a803b203aaced)
- GraphSense balance: 20,525.69 ETH

This also affects the balance and received child property boxes.

Probably a problem in BTC vs. ETH denomination conversion.

**Comment by defconst** [comment]
```
 address_id_group | address_id | balance
------------------+------------+--------------------
             1581 |   39548512 | 205508355000000000
```

**Comment by mdragaschnig** [comment]
Comparing cassandra balance to ETH client:
2021-11-23 11:16:53 INFO     0x564286362092d8e7936f0549571a803b203aaced balance: 205508355000000000 OK

**Comment by myrho** [comment]
fixed in rest

**Comment by mdragaschnig** [comment]
Note: Etherscan shows only the most recent balance.
 
So when comparing Graphsense balances with Etherscan take care to only compare accounts with **no** activity **after** Graphsense "Last update" timestamp on landing page.
