### ISSUE TITLE
Address View | Transaction Child View | Scrolling down tx table fails

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#247]
When scrolling down the transaction table with > 10.000 entries using the slider, the next page is not displayed.
[2021-11-23 14-31-00.report.pdf](https://github.com/graphsense/graphsense-dashboard/files/7588321/2021-11-23.14-31-00.report.pdf)

**Comment by mdragaschnig** [comment]
On Firefox 94.0 and Chrome 96.0.4664.45 still hangs when scrolling down with slider (after a few thousand rows).
![eth-scroll4](https://user-images.githubusercontent.com/47592782/143444489-f7a9a03e-360f-4ef2-bbb4-b4f1eb27e677.png)

ETH 0xddfabcdc4d8ffc6d5beaf154f18b778f892a0740
