### ISSUE TITLE
Address View | Receiving / Sending addresses detail view

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#248]
Currently that view shows the columns "received", which could be mis-interpreted as the amount received from the focus address. I think we should instead display the estimated value transferred (= property of the edge).

**Comment by behas** [comment]
with ETH, for "received" we show only sums computed over external transactions. Currently, we ignore mining revenues and internal transactions.

**Comment by behas** [comment]
Instead of Received / Spent, the property box should display the following columns:

For addresses:
- Outgoing Address | Label | Address balance | Address Received | No. Transactions | Estimated Value

For entities:
- Outgoing Entity | Label | Entity balance | Entity Received | Entity No. Addresses | No. Transactions | Estimated Value

**Comment by myrho** [comment]
Fixed, column "Entity No. addresses" still missing though. Would fix this with https://github.com/graphsense/graphsense-REST/issues/48
