### ISSUE TITLE
Display session expiration time

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#252]
Currently the user is not informed when the session expires and the key must be entered again. Consequently, subsequent request might fail because of missing authentication.

Proposed solution: display remaining time next to request limit; change colours (green-yellow-red) when it approaches expiration. Ideally, add a renew button.

**Comment by soad003** [comment]
in the latest release limits are shown in the dashboard setting

![image](https://github.com/user-attachments/assets/862fbb25-027a-45d9-9c98-00e665b2ce22)
