### ISSUE TITLE
Entity Transaction Property Box | Wrong conversion

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#253]
There seems to be a conversion error in the entity-transaction property box. Values are not plausible; too high.

![image](https://user-images.githubusercontent.com/366981/143215275-a3e69b89-6262-4bdd-ab46-508b10a63815.png)
[2021-11-24 10-48-39.report.pdf](https://github.com/graphsense/graphsense-dashboard/files/7594563/2021-11-24.10-48-39.report.pdf)

**Comment by mdragaschnig** [comment]
Edge value corresponds to value in property box

![btc-conversion](https://user-images.githubusercontent.com/47592782/143453167-22b58b36-bad8-4747-9a09-90ddd4198e7b.png)
