### ISSUE TITLE
Search by category returns unexpected matches

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#255]
Search by category "coinjoin" returns exchange nodes, which is somehow unexpected. If no nodes of type x are found, search shouldn't return anythin
[2021-11-24 11-40-14.report.pdf](https://github.com/graphsense/graphsense-dashboard/files/7594974/2021-11-24.11-40-14.report.pdf)
g.

**Comment by myrho** [comment]
That's because address tags of found entities match "coinjoin".
Should the search only consider entity tags?

**Comment by behas** [comment]
Actually yes, if I start my search from an entity, I would like to consider entity tags only. Maybe this should be a configuration option?

**Comment by myrho** [comment]
Search is currently only possible on the entity level anyways.

**Comment by myrho** [comment]
fixed in rest
