### ISSUE TITLE
Indicate address tag availability

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#275]

**Comment by behas** [comment]
Currently entity tags are displayed only if an address tag is propagated to the entity level. However, there should also be an indicator (a tag symbol) for cases when address tags are available but not propagated to the entity level.

**Comment by behas** [comment]
this already worked and somehow disappeared.

**Comment by myrho** [comment]
it still does?


![Image](https://user-images.githubusercontent.com/1172181/175367574-2e2faf37-0119-41eb-88a2-4a017d948bef.png)

**Comment by behas** [comment]
ah..true. I somehow expected that all tagged clusters carry that symbol. Also those that carry a cluster_definer tag. Can we add this easily?

**Comment by myrho** [comment]
Fixed
