### ISSUE TITLE
Search results redesign

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#278]

**Comment by behas** [comment]
When searching for a label, search results currently list only address tags. However, we also need to group them by entity/cluster. This is kind of important.

Suggestion:

- Label search returns a parent property box with the following fields: "Search term", "Addresses", "Clusters"
- When clicking on "Addresses" a child property box opens and lists the matching address tags
- When clicking on "Clusters" a child property box opens and lists the matching clusters; if we can somehow distinguish between those that carry a propagated cluster tag and those that don't even better (maybe a flag)

**Comment by myrho** [comment]
I think we should stick to the notion that tags only apply to certain addresses. So how about listing address tags which have cluster_definer true when clicking "Clusters"?

**Comment by behas** [comment]
True, but a standard search use case is: find all clusters controlled by a certain provider and put them on the dashboard. Currently, this is not possible.

Possible easy fix: also display the cluster id as part of the search results and allow sorting by cluster id.
