### ISSUE TITLE
Attribution Tags property box fields

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#279]
The attribution tags property box should display the following fields

- Address
- Label 
- Source (if uri -> hyperlink)
- Category
- Abuse
- Confidence score (integer) / sorted
- TagPack (tagpack.title; with hyperlink to tagpack.uri if available)
- Creator (tagpack.creator)

Further features:
- it should be possible to sort by confidence
- if a tag defines a cluster it should be coloured (as it is already the case)

**Comment by mdragaschnig** [comment]
tagpack-tool has been updated for tagpack URI  accordingly:
table **tagpack** has a new field named **uri**

**Comment by mdragaschnig** [comment]
@myrho 
@defconst  and I have updated the iknaio tagstore, the uri field is available for you to start developing.

**Comment by behas** [comment]
Please check TagPack links

**Comment by mdragaschnig** [comment]
For public TagPacks it should point to the corresponding TagPack file in Github.
OK  For private TagPacks there shouldn't be any link.

**Comment by myrho** [comment]
@mdragaschnig close?
