### ISSUE TITLE
Dashboard rewrite

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#287]
### Architectural:
- [x] ●● Layout
- [x] ● URL navigation
- [x] ● Status bar
- [x] ●● Logger
- [x] ● **Side bar**
- [x] ●● **Plugable**

### General:
- [x] ●● Search bar 
- [x] ● Statistics page

### User options:
- [x] ● Request limit display
- [x] ● Language switch
- [x] ● **Currency switch**
- [x] ● Logout

### Graph:
- [x] ●●● draw graph nodes
- [x] ● Expand graph
- [x] ●● draw links
- [x] ● **draw link labels**
- [x] ● **move entity nodes**
- [x] ● **Expand entity addresses**
- [x] ● **select nodes**
- [x] ● ~~multi-select nodes~~
- [x] ● **display property box**
- [x] ●●● **annotate nodes**
- [x] ● ~~sort addresses by properties~~
- [x] ●● **Neighbor search**
- [x] ● Remove nodes
- [x] Shadow links
- [x] Highlight links on hovering nodes

### Data tables:
- [x] ●● **draw tables**
- [x] ● infinite scrolling
- [x] ● **sort table**
- [x] ● **search table**
- [x] ● **load things from table row into graph**
- [x] ● ~~bulk load things from table into graph~~
- [x] ● ~~download table as csv~~
- [x] highlight cluster definer tags
- [x] mark nodes in tables if visible in graph

### Tools:
- [x] ● new graph
- [x] ●● **import options**
- [x] ●● **export options**
- [x] ● Undo/Redo
- [x] ●● Highlighter
- [x] ● **Graph options (label display, ...)**
- [x] ● **Legend**

### Case management:
- [x] ● **Add case**
- [x] ● **Tag nodes for case**
- [x] ● ~~Tag seed addresses for case~~
- [x] ●● Search cases
- [x] ● **Case property box**
- [x] ● **Case data table (cases assoc. with node)**
- [x] ● **Case addresses data table**

**Comment by behas** [comment]
let's skip the multi-select nodes feature for the moment (was hardly ever used)

**Comment by behas** [comment]
Also, let's move case management issues to Iknaio.
