### ISSUE TITLE
Improve entity label + id display

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#295]
Improve display of entity ID / label.

Suggestion:

For known entities: show label + entity id in smaller font-size and greyed out in parenthesis
For unknown entities: show "Unknown" + same as above

Maybe we could, at a later point, also display "Partially known" entities = those that have tags but no tag propagated on the cluster level. To be discussed.

**Comment by myrho** [comment]
do we really need the entity id displayed in the graph? The user could retrieve it in the property box anyways. I'm asking because placing differently sized labels in this narrow space is tricky, esp. because the entity label could be long, taking 2 lines.

**Comment by behas** [comment]
No, not in the graph; I mean the property box.

**Comment by behas** [comment]
Looks perfectly now.
