### ISSUE TITLE
Minor dashboard improvements

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#297]
General:

- [x] Property boxes should have light blue borders (as in the old dashboard)
- [x] Decrease font size (I always zoom out by default) 

Link Transaction View
- [x] Height of child property box is currently determined by parent box (which is too small); introduce a min height

Graph / Cluster Boxes:
- [x] Restrict max label length (some labels might be long and overlap with the currency indicator)

Clusters / address tagged with private tags:
- [x] Add lock symbol in graph boxes
- [x] Add "Locked Label" to property

Landing Page
- [x] "ledger statistics" -> "Ledger Statistics"

**Comment by myrho** [comment]
isn't the last point covered by #275 ?

**Comment by behas** [comment]
true.

**Comment by behas** [comment]
Ad link transaction view: too much vertical space between properties in parent box.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/366981/175831574-bb4cbef3-442a-4206-a6cd-f77e5b94dcdb.png">
