### ISSUE TITLE
Incoming entity labels not shown in property box

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#313]
Sending entities child view doesn't display labels of known entities.

Example entity root address: 1DXiEDqfwNCwuad27E9wBBuTYiKYnY7ZRQ

**Comment by myrho** [comment]
This entity has 3115 sending entities, so I've limited the retrieved neighbors by a certain id:
```
curl -X 'GET' \
  'http://localhost:9000/btc/entities/263532917/neighbors?direction=in&only_ids=319021677&include_labels=true&pagesize=10' \
  -H 'accept: application/json'
```
yields the entity with labels as expected.

**Comment by behas** [comment]
close or postpone?

**Comment by behas** [comment]
This is still an open issue. In the dashboard the incoming / outgoing entity property boxes do not show known labels.
