### ISSUE TITLE
Retrieving an address list for a medium-size cluster takes >1 minute

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-dashboard#323]
Retrieving an address list for a medium-size cluster (1656 addresses, Cluster ID: 164754269, example address: 1CGA4srJbPWhtJb7ezgY6GQf4PKhFuzD9w) takes a very long time, greater than one minute.

This is new behaviour,  it worked fine three months ago.

**Comment by myrho** [comment]
Can't reproduce, maybe there was temporary overload?
