### ISSUE TITLE
Wide tables not scrollable on small viewports

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#325]
![image](https://user-images.githubusercontent.com/1172181/182146534-9d26f371-42db-47b5-a812-e2da870bfd20.png)

**Comment by behas** [comment]
We could abbreviate addresses and put a copy-to-clipboard icon next to it.

E.g., "17vzpL7n29egdeJF1hvUE4tKV81MqsW4wF" -> "17vzpL...W4wF" (cp symbol).

The same would work for transactions.
