### ISSUE TITLE
Show link between two addresses if it exists

### ISSUE THREAD

**Issue by MatteoRomiti** [graphsense/graphsense-dashboard#34]
If we look for an address and then we add another address to the graph using the search bar above, the link between the two addresses is not shown by default, am I right?
I think it would be useful to immediately see the connection, if it exists.

**Comment by MatteoRomiti** [comment]
Two addresses to use as an example:
1NAQAwjEqUEWr7snz4Rq2PSPYTbYn7TY3F
16GtJgW9XmRrvyJL7SaiuYMAYcmDVAcsT2

**Comment by behas** [comment]
related to #37

**Comment by myrho** [comment]
Direct links will be shown when https://github.com/graphsense/graphsense-transformation/issues/11 is fixed.
