### ISSUE TITLE
docker-compose build does not work 

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-dashboard#341]
Step 15/21 : COPY ./plugins $WORKDIR/plugins
ERROR: Service 'graphsense-dashboard' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat plugins: file does not exist

**Comment by yaz1** [comment]
I am experiencing the same issue. The plugin folder is excluded in the .gitignore file

**Comment by myrho** [comment]
Thank you for reporting! As a workaround just create an empty plugin folder.

**Comment by mdragaschnig** [comment]
> Thank you for reporting! As a workaround just create an empty plugin folder.

Now fails with

Step 17/20 : RUN npm run build &&     mkdir -p /usr/share/nginx/html /run/nginx &&     mv $WORKDIR/dist/* /usr/share/nginx/html/ &&     rm -rf /root/.config /root/.npm &&     rm -f /etc/nginx/http.d/default.conf &&     apk del build-dependendencies
 ---> Running in 68d10a1546df

> vite-elm-template@1.1.2 prebuild
> elm-tooling install

/app/elm-tooling.json
elm 0.19.1: all good
elm-format 0.8.5: all good
elm-json 0.2.8: all good
elm-test-rs 2.0.0: all good

> vite-elm-template@1.1.2 build
> vite build

vite v2.9.0 building for production...
transforming...
✓ 3 modules transformed.
**Could not resolve '../plugins/casemgm/generated/index.js' from src/main.js
error during build:
Error: Could not resolve '../plugins/casemgm/generated/index.js' from src/main.js**
    at error (/app/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/app/node_modules/rollup/dist/shared/rollup.js:22320:24)
    at /app/node_modules/rollup/dist/shared/rollup.js:22299:26
ERROR: Service 'graphsense-dashboard' failed to build: The command '/bin/sh -c npm run build &&     mkdir -p /usr/share/nginx/html /run/nginx &&     mv $WORKDIR/dist/* /usr/share/nginx/html/ &&     rm -rf /root/.config /root/.npm &&     rm -f /etc/nginx/http.d/default.conf &&     apk del build-dependendencies' returned a non-zero code: 1

**Comment by yaz1** [comment]
> casemgm

Thank you for your reply. Creating an empty folder won't work because looking at the elm.json, it is importing 
`
"plugins/casemgm/generated",
        "plugins/casemgm/src"
`
It is maybe a library dependency because plugin is imported many times in the code, but unfortunately, I am not familiar with elm lang to know the possible workarounds.

**Comment by myrho** [comment]
I've decoupled these plugin related things. Please try again with branch `develop`.

**Comment by yaz1** [comment]
Thank you. It is working now with local setup. Unfortunately, I am getting another error but it is related to the REST api because it is referencing  a view "cluster_defining_tags_by_frequency_and_maxconfidence" that is not created in tagpack tool. I will report the issue there.

**Comment by myrho** [comment]
Good to hear. So I'll close this issue now.
