### ISSUE TITLE
Error when loading specific ETH address

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#344]
Certain ETH addresses (e.g., 0xdddbac89f9400ee11d8cd7af9efa1934f776b874) are found when searching, but yield and error when loading details.

**Comment by defconst** [comment]
0xdddbac89f9400ee11d8cd7af9efa1934f776b874 has only one non-external tx (EOA to Contract creation) 
https://etherscan.io/address/0xdddbac89f9400ee11d8cd7af9efa1934f776b874
