### ISSUE TITLE
Source link preview

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#356]
Some source links are [bit.ly](http://bit.ly/) links and he indicated it might be good to show (when hovering over de link) where you are redirected to, as you do not wat to be forwarded to some site that you do not trust.

**Comment by myrho** [comment]
According to https://support.bitly.com/hc/en-us/articles/230650447-Can-I-preview-a-link-before-clicking-on-it- this should be solved in the data, ie. append "+" to the bit.ly url.
