### ISSUE TITLE
Cluster relations not expanding when targets are addresses

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#37]
e.g., clicking on the 173 outgoing cluster relations of https://demo.graphsense.info/#!btc/cluster/17642139

does not work because targets are addresses and not clusters

**Comment by myrho** [comment]
Will be fixed via https://github.com/graphsense/graphsense-transformation/issues/11

**Comment by defconst** [comment]
Fixed in https://github.com/graphsense/graphsense-transformation/commit/e662614ee9091ea138d09ab7162d64899ce77af0
