### ISSUE TITLE
Add token currencies on statistics page

### ISSUE THREAD

**Issue by soad003** [graphsense/graphsense-dashboard#382]

**Comment by behas** [comment]
I propose an asset-centric approach and list supported assets, e.g.: BTC, LTC, ETH/ETH, USDT/ETH, USDT/TRON, etc.

**Comment by behas** [comment]
We should also mention on the Website and in a more visible place what asset types we are supporting.

**Comment by soad003** [comment]
Apart from making it clear which assets we support we postpone this topic. Little users are interested in the detailed statistics and since the last release the page is now not immediately user facing anymore (stags page). So other than the more prominent positioning of the supported currencies no changes are planned.
