### ISSUE TITLE
Enable basic tx-level tracing

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#387]
Currently, tracing is possible only on the address-graph level, i.e., by following the sending and receiving addresses. We could enable a basic form of tx-level tracing by utilizing the "Transactions" field in the property box. Necessary steps:

- [] Split "Transactions" into "Incoming Txs" and "Outgoing Txs"
- [] For "Incoming Txs" display the number of "Input Addresses" and allow expansion of address + value in another child-level box
- [] For "Outgoing Txs" display the number of "Output Addresses" and allow expansion of address + valuein another child-level box
- [] Enable selection of addresses to be added to the dashboard

**Comment by soad003** [comment]
might be a duplicate with https://github.com/graphsense/graphsense-dashboard/issues/402
