### ISSUE TITLE
export csv: coin values as floats (big currency)

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#389]
it is not obvious that coin values are exported as satoshis, not btc.

**Comment by soad003** [comment]
I would not export values as floats as default since its a lossy process.

**Comment by soad003** [comment]
Ok, after discussions. Might be ok to do since easier for the users. Longer term; provide both options

**Comment by soad003** [comment]
Now the export provides both, the base satoshi, wei values as well as converted to the base currency (btc, eth) as floats.  In that turn i also changed that timesamps are exported as dates not as ints.

**Comment by soad003** [comment]
Fixed in 4c0e18702fe414c8bf19eb7e2e7fd49e3ad184b2
