### ISSUE TITLE
Feature proposal: Display specific transaction as link between nodes 

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#391]
Users want to display only a specific transaction between nodes. 
One way to get to this could be the following:
1. Extend the address txs table by the no. inputs/outputs:
![image](https://user-images.githubusercontent.com/1172181/233039544-80d6bd28-23cd-4fa7-951d-f109ac2c3d74.png)

2. Make the no. inputs/outpus clickable. On click another table with the resp. addresses is shown next to the txs table:
![image](https://user-images.githubusercontent.com/1172181/233040709-57e720ea-89ae-4dea-b663-be6062cbeb0c.png)

3. On click on an address there, it is added to the graph with a dashed edge in between (or whatever):
![image](https://user-images.githubusercontent.com/1172181/233042110-0064e9d1-e0eb-4ca9-8876-11a5857690b9.png)

**Comment by behas** [comment]
Had a similar approach in mind. We should visually distinguish between ``transaction'' and ``relation edges'' and maybe even let the user choose the level of abstraction: tx-graph vs. address-graph vs. cluster-graph.

**Comment by soad003** [comment]
I upvote on "the let the user decide which abstraction to chose".  Regarding the clickable inputs and outputs i would add some kind of symbol to indicate that there is an action hidden (maybe also the dots).

**Comment by behas** [comment]
I think this is getting increasingly important and I will create a more general issue "Introduce Transaction Graph" which subsumes this issue.

**Comment by soad003** [comment]
We started a project working on the transaction graph. Since it will take some time, and divided the task into multiple issues
https://github.com/graphsense/graphsense-dashboard/issues/443 https://github.com/graphsense/graphsense-dashboard/issues/446 https://github.com/graphsense/graphsense-dashboard/issues/445 ...

So i am closing this.
