### ISSUE TITLE
Loading multiple addresses stops if address already visible

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#394]
here is the possibility to insert more than one address in the search bar. But in case I add an address that have already been displayed, then the graph add only all addresses until the one that is already in the graph. Sample:

Step 1: addresses below will be inserted into the search bar
3EFCgArpMVVNUTydLLErNzMzukx1oknYQZ (not on the dashboard)
31om3g8agy8ivVCnYe5rco4hTJS4BNkL2F (already on the dashboard)
3HevDcrodsHn7dL4r4hEjV2FadpeUNmgd2 (not on the dashboard)
36rW7SPiiDFmrvxoHSbP7n4BoA5S96QTGm (not on the dashboard)

Step 2: the addresses below will appear on the the dashboard
3EFCgArpMVVNUTydLLErNzMzukx1oknYQZ (on the dashboard)
31om3g8agy8ivVCnYe5rco4hTJS4BNkL2F (on the dashboard)
3HevDcrodsHn7dL4r4hEjV2FadpeUNmgd2 (not on the dashboard)
36rW7SPiiDFmrvxoHSbP7n4BoA5S96QTGm (not on the dashboard)

**Comment by soad003** [comment]
Could not entirely reproduce this issue. In my case it consistently inserted all nodes, but the last two nodes were inserted  out of the viewport of the graph so it looked like nothing was inserted. I added code to center the graph after a new address was inserted iif the bbox of the layers grows out of the viewport. This helps avoiding the confusion.
