### ISSUE TITLE
Introduce Transaction Graph

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#402]
Here some initial ideas how I would implement that:

- the user can choose the graph abstraction level in a dropdown box (tx-graph, addr-graph, cluster-graph)
- depending on the abstraction level, different properties are shown in the property box; in the addr-graph and cluster-graph views we show incoming and outgoing relations (aggregations, as they are now), in the tx-graph view we show transactions
- in the graph, transactions are visually distinct, e.g., dashed arrows
- the transaction graph only interacts with the raw tx keyspace and is therefore updated in real-time; all the aggregations are, per definition, delayed and might be greyed out if not yet computed. In that way we can solve the real-time issue quite easily.

(This enhancement will likely be a release on its own).

**Comment by soad003** [comment]
Rest will allow to query tx refs in the next release (see [d8fa505](https://github.com/graphsense/graphsense-REST/pull/95))

**Comment by soad003** [comment]
We started a project working on this issue since it will take some time, and divided the task into multiple issues
#443 #446 #445 ...

So i am closing this.
