### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#44]
It should be possible to export all tables as CSV

**Comment by myrho** [comment]
depends on graphsense/graphsense-rest#4

**Comment by myrho** [comment]
need to wrap authorization in a service worker. After clicking a generated download link, sw attaches authorization headers.

**Comment by myrho** [comment]
naah that neither works. other possiblities:
* put jwt token in session cookie
* put jwt token in URL of the download link
