### ISSUE TITLE
Support PNG download

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#448]
Currently the user can download .svg images of created graphs. However, hardly any tool supports processing of .svg files. Therefore, I propose to also support .png download, making this the primary option. If possible, we should also crop the viewport around a graph.

**Comment by soad003** [comment]
I have implemented a simple version of this here. https://github.com/graphsense/graphsense-dashboard/commit/3a58090652fed236bf15c6de94a18053afcf186b

styling is not perfect yet.
