### ISSUE TITLE
show tags in address/cluster table

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#54]
add column

**Comment by myrho** [comment]
That actually needs querying address_tags/cluster_tags for each address/cluster. 

Is this really what we want? Or are tags meant to be added to the property box? @behas

**Comment by myrho** [comment]
Should be a precalculated field "tags" containing a derivative of the list of tags belonging to a node. See graphsense/graphsense-transformation#15

**Comment by behas** [comment]
Add a separate column (tags) showing up to 2 comma-separated labels. If there are more than two tags, open child view.

**Comment by myrho** [comment]
move label column next to entity/address id
