### ISSUE TITLE
Option to export/import user-defined labels

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#64]
so users can reapply their labels on other graphs.

**Comment by behas** [comment]
Very low priority. I propose to skip that one.

**Comment by myrho** [comment]
format: tagpack yml

title: User Defined Tagpack
creator: graphsense username
description: 
lastmod: 2019-03-15
tags:
    - address: 1Archive1n2C579dMsAu3iC6tWzuQJz8dN
      currency: BTC
      note: "the note"
      (label, category, source auslassen)

    - address: 1K1rgZ1dz9w7dsR1HGS1drmzfUHMtqx1Tc
      currency: BCH
    - address: "0xFA8E3920daF271daB92Be9B87d9998DDd94FEF08"
      currency: ETH
    - address: rGeyCsqc6vKXuyTGF39WJxmTRemoV3c97h
      currency: XRP
    - address: t1ZmpK4QFcvyQZ3ghTgSboBW8b4HgiZHQF9
      currency: ZEC
      lastmod: 2019-04-16
