### ISSUE TITLE
Configurable colour assignment for categories

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-dashboard#73]
Now categories are hardcoded. Perhaps have them dynamic by what is present in the graph? Somehow need to make sure that category colors remain the same across graphs.

**Comment by behas** [comment]
For each category listed in a tag-pack config file, it should be possible to define some colour code. Maybe in the dashboard config file.

Automated colouring should be the fallback for undefined categories,

**Comment by myrho** [comment]
have local config file that maps categories to colors at build time

fetch categories at run time for the legend and to assign random colors for un-configured categories
