### ISSUE TITLE
Add max. addresses / outgoing edges as config option to search incoming / outgoing

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#76]
In many cases it does not make sense to go deeper when hitting a node with more than X (e.g., 1000) outgoing edges because this is most probably an exchange.

Suggestion: add max. outgoing nodes to context menu config and consider this when traversing the graph. Using that restriction it would be possible to go deeper than 3 steps

**Comment by myrho** [comment]
improve setting of breadth value (< skipNumNeighbors)

**Comment by myrho** [comment]
criterion for skipping a node is its number of addresses, not neighbors

**Comment by myrho** [comment]
done
