### ISSUE TITLE
Showing Transaction Details

### ISSUE THREAD

**Issue by PatrickSchre** [graphsense/graphsense-dashboard#85]
To view some transaction details by clicking the connection between 2 addresses.
I.e. there are 4 tx, after clicking the connection, these 4 tx are shown in the box with their timestamps and amounts which were transferred.

**Comment by behas** [comment]
This can be done as follows:

1.) Store plain relations (between address and entity nodes) during transformation
2.) Provide REST interface method
3.) Implement corresponding view in Dashboard

**Comment by myrho** [comment]
Could it also be solved by doing the following automatically in one step:
* bringing up the prop box of the node from which the clicked tx goes out
* opening the transactions table of this node
* filtering the transactions by destination node id equals the incoming node of the clicked tx

However, destination node needs to be precalculated for the transaction table then. I fear, there can be more than 1 destination node per transaction right?

**Comment by behas** [comment]
This might work for low-degree nodes but not for those with many incoming and outgoing transactions (e.g, exchanges). We have to precompute those tables with src and dst as primary key.

The question is what other properties we need next to txid, timestamp, and value.

**Comment by MatteoRomiti** [comment]
Also, at the moment, it is not possible to distinguish between incoming and outgoing transactions. This address 35hK24tcLEWcgNA4JxpvbkNkoAcDGqQPsP, for example, has many incoming and few outgoing and there is no way to quickly find the outgoing ones.

**Comment by myrho** [comment]
It's not obvious, but incoming tx have positive, outgoing tx a negative value (in the tx table).

**Comment by MatteoRomiti** [comment]
That is indeed a possible way to do it. I don't know how relevant it can be, but if there is a tx that has address A1 both among the inputs and the outputs, then we have no way to distinguish it. Should I provide an API call for this in/out txs?

**Comment by MatteoRomiti** [comment]
Also, at the moment, at the entity level, we have no information about txs, we only have relations (aggregated data). If we want to get tx ids, we need to be at the address level and then apply some filtering.

**Comment by myrho** [comment]
Hm, I don't get your point. How does it relate to the initial intend of this issue?

**Comment by MatteoRomiti** [comment]
It was not clear to me on which level you want to have the txs, because the issue was on an address-to-address level, but then the conversation introduced also entities. (I hope this was what you were asking).

**Comment by behas** [comment]
We must annotate each address / cluster graph edge with an additional property `tx_ids`, which lists the set of transactions between a given source and target.

We could introduce a cut-off at x tx_ids.

@defconst please compute the distribution first.

**Comment by defconst** [comment]
Runtime: increase 12.8 -> 15.8h (Bitcoin block height 619442, txLimit=100)

![Spark Cache](https://imgur.com/cUDAsVy)

**Comment by myrho** [comment]
show source and target address/entity id in property box + table of transactions between these two.
If there are more than 100 tx, show a note in the property box.
