### ISSUE TITLE
Add "empty workspace" or "import" button to landing page

### ISSUE THREAD

**Issue by MatteoRomiti** [graphsense/graphsense-dashboard#93]
At the moment, if I want to import a .gs file, I cannot do it from the landing page. I first have to search for something and then click the import button. It would be nice to be able to import a file directly from the landing page.

**Comment by myrho** [comment]
Actually since we have the login form on the landing page, I think it'd be more concise to forward the user to the app after login instead of showing just the search bar.

**Comment by MatteoRomiti** [comment]
I agree

**Comment by behas** [comment]
I suggest to keep the landing page and add a link (in the top right corner) that allows the (advanced) user to directly jump (back) to the (empty) dashboard
