### ISSUE TITLE
Regional settings on Mac OSX bugs the Dashboard

### ISSUE THREAD

**Issue by VinceICPO** [graphsense/graphsense-dashboard#96]
**The issue**
If your your Mac is set to French (and maybe other languages too?), the Dashboard will fail to load in Safari, Firefox and Chrome.
You will know it fails because the dashboard does not display the 4 infographic bubbles for BTC, BCH, LTC and ZEC. Any searches will fail to give results. The dev. console displays errors.

_This is quite severe because new users who are testing cannot see this is an incorrect behaviour and just think there is no result to their queries..._

**Work around**
Go to your Macbook system preferences | language and regional settings | Apps | Add Safari and configure it to English.

#bug

**Comment by behas** [comment]
that's fixed and will be deployed with the next release.
