### ISSUE TITLE
Gray out addresses without transactions

### ISSUE THREAD

**Issue by MatteoRomiti** [graphsense/graphsense-dashboard#98]
There are some TagPacks that contain addresses that are not in GraphSense because they didn't receive money yet. An example is 115aKRPmvg9hxsVr8sop8SYWd8K72K4kxi which is related to sextortion. At the moment, if in the dashboard I enter "sextortion excello", I can correctly find it in the list, but if I click it, nothing happens because it is not found from the rest. Would it make sense or is it possible to gray out addresses that didn't receive any money?

**Comment by behas** [comment]
This requires another field computed during the transformation step. It should indicate whether an address is active or not.

@defconst please implement this in the step that produces the `address_tags` table.

**Comment by myrho** [comment]
Activity state returned by `/labels/locky/tags`
